sudo: required

services:
    - docker

before_install:
    - docker build -t mritunjayonemail/docker-react-test -f Dockerfile.dev .
    
script:
    - docker run -e CI=true mritunjayonemail/docker-react-test npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-326299347197"
    bucket_path: "docker-react-test"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    